{application,finch,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,mint,castore,
                             nimble_pool,nimble_options,telemetry,mime]},
              {description,"An HTTP client focused on performance."},
              {modules,['Elixir.Finch','Elixir.Finch.Error',
                        'Elixir.Finch.HTTP1.Conn','Elixir.Finch.HTTP1.Pool',
                        'Elixir.Finch.HTTP1.PoolMetrics',
                        'Elixir.Finch.HTTP2.Pool',
                        'Elixir.Finch.HTTP2.PoolMetrics',
                        'Elixir.Finch.HTTP2.RequestStream',
                        'Elixir.Finch.Pool','Elixir.Finch.PoolManager',
                        'Elixir.Finch.Request','Elixir.Finch.Response',
                        'Elixir.Finch.SSL','Elixir.Finch.Telemetry']},
              {registered,[]},
              {vsn,"0.18.0"}]}.
