{application,phoenix_live_reload,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,phoenix,file_system]},
              {description,"Provides live-reload functionality for Phoenix"},
              {modules,['Elixir.Phoenix.LiveReloader',
                        'Elixir.Phoenix.LiveReloader.Application',
                        'Elixir.Phoenix.LiveReloader.Channel',
                        'Elixir.Phoenix.LiveReloader.Socket',
                        'Elixir.Phoenix.LiveReloader.WebConsoleLogger']},
              {registered,[]},
              {vsn,"1.5.3"},
              {mod,{'Elixir.Phoenix.LiveReloader.Application',[]}}]}.
